[package]
name = "onnx-test-suite"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
bytes = "0.5"
fs2 = "0.4"
log = "0.4.6"
prost = "0.6"
tract-core = { path = "../../core", features = [ "paranoid_assertions" ] }
tract-nnef = { path = "../../nnef" }
tract-onnx = { path = "../../onnx" }

[features]
onnx_1_4_1 = []
onnx_1_5_0 = []
onnx_1_6_0 = []
onnx_1_7_0 = []
default = [ "onnx_1_7_0" ]

[dev-dependencies]
env_logger = "0.7"

[build-dependencies]
fs2 = "0.4"
