[package]
name = "tract-linalg"
version = "0.11.2-pre"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
derive-new = "0.5"
dyn-clone = "1"
half = "1.3"
educe = "=0.4.11" # locked for rust 1.41.0
lazy_static = "1.3"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
tract-data = { path = "../data" }

[build-dependencies]
cc = "1.0"
liquid = "0.21"
unicode-normalization = "0.1"
smallvec = "1"

[dev-dependencies]
criterion = "0.3"
proptest = "0.10"

[[bench]]
name = "mat_vec"
harness = false

[[bench]]
name = "mm_for_wavenet_hw"
harness = false

[[bench]]
name = "conv_for_wavenet_hw"
harness = false

[[bench]]
name = "mm_for_inception"
harness = false

[[bench]]
name = "mm_for_asr_am"
harness = false

[[bench]]
name = "sigmoid"
harness = false
