name: Full test harness

on:
  push:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          target
          .cache
        key: ${{ runner.os }}-cargo-${{matrix.rust}}-2
    - name: Full test 
      run: .travis/native.sh
